name: github-pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy the demo site to GitHub Pages
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 8.15.0
        uses: actions/setup-node@v1
        with:
          node-version: 8.15.0

      - run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        with:
          emptyCommits: false
          keepFiles: true
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs
