name: Check for lint errors, run tests and upload coverage
on:
  push:
    branches:
     - "*"
  pull_request:
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 8.15.0
      uses: actions/setup-node@v1
      with:
        node-version: 8.15.0

    - run: yarn install

    - name: Check for lint errors
      run: yarn lint --no-fix

    - name: Run tests
      if: success()
      run: yarn test:coverage
      env:
        CI: true

    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.2
      if: success()
      with:
        token: "${{ secrets.CODECOV_TOKEN }}"
